const FLEX_ZONES = [
  { localidad: "20 de Junio", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "3 de Febrero", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "9 de Abril", zona: "Zona 3 - Esteban Echeverría", importe: 5500 },
  { localidad: "Acassuso", zona: "Zona 2 - San Isidro", importe: 4600 },
  { localidad: "Adrogué", zona: "Zona 3 - Almirante Brown", importe: 5500 },
  { localidad: "Agronomía", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Aldo Bonzi", zona: "Zona 2 - La Matanza Norte", importe: 4600 },
  { localidad: "Alejandro Korn", zona: "Zona 4 - San Vicente", importe: 7800 },
  { localidad: "Almagro", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Almirante Brown", zona: "Zona 3 - Almirante Brown", importe: 5500 },
  { localidad: "Altos de San Lorenzo", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "Avellaneda", zona: "Zona 2 - Avellaneda", importe: 4600 },
  { localidad: "Avellaneda Centro", zona: "Zona 2 - Avellaneda", importe: 4600 },
  { localidad: "Balvanera", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Banfield", zona: "Zona 2 - Lomas de Zamora", importe: 4600 },
  { localidad: "Barracas", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Beccar", zona: "Zona 2 - San Isidro", importe: 4600 },
  { localidad: "Belgrano", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Bella Vista", zona: "Zona 3 - San Miguel", importe: 5500 },
  { localidad: "Belén de Escobar", zona: "Zona 4 - Escobar", importe: 7800 },
  { localidad: "Benavídez", zona: "Zona 3 - Tigre", importe: 5500 },
  { localidad: "Berazategui", zona: "Zona 3 - Berazategui", importe: 5500 },
  { localidad: "Berisso", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "Bernal", zona: "Zona 3 - Quilmes", importe: 5500 },
  { localidad: "Billinghurst", zona: "Zona 2 - San Martín", importe: 4600 },
  { localidad: "Boedo", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Bosques", zona: "Zona 3 - Florencio Varela", importe: 5500 },
  { localidad: "Boulogne", zona: "Zona 2 - San Isidro", importe: 4600 },
  { localidad: "Burzaco", zona: "Zona 3 - Almirante Brown", importe: 5500 },
  { localidad: "CABA", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Caballito", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Campana", zona: "Zona 4 - Campana", importe: 7800 },
  { localidad: "Campana Centro", zona: "Zona 4 - Campana", importe: 7800 },
  { localidad: "Canning (E. Echeverría)", zona: "Zona 3 - Esteban Echeverría", importe: 5500 },
  { localidad: "Canning (Ezeiza)", zona: "Zona 3 - Ezeiza", importe: 5500 },
  { localidad: "Capital Federal", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Carapachay", zona: "Zona 2 - Vicente López", importe: 4600 },
  { localidad: "Carlos Keen", zona: "Zona 4 - Luján", importe: 7800 },
  { localidad: "Carlos Spegazzini", zona: "Zona 3 - Ezeiza", importe: 5500 },
  { localidad: "Casanova", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "Caseros", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Castelar", zona: "Zona 2 - Morón", importe: 4600 },
  { localidad: "Cañuelas", zona: "Zona 4 - Cañuelas", importe: 7800 },
  { localidad: "Cañuelas Centro", zona: "Zona 4 - Cañuelas", importe: 7800 },
  { localidad: "Celina", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "Chacarita", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Champagnat", zona: "Zona 4 - Pilar", importe: 7800 },
  { localidad: "Churruca", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "City Bell", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "Ciudad Evita", zona: "Zona 2 - La Matanza Norte", importe: 4600 },
  { localidad: "Ciudad Jardín El Palomar", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Ciudad Jardín Lomas del Palomar", zona: "Zona 2 - San Martín", importe: 4600 },
  { localidad: "Ciudadela", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Claypole", zona: "Zona 3 - Almirante Brown", importe: 5500 },
  { localidad: "Coghlan", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Colegiales", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Constitución", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Cortínez", zona: "Zona 4 - Luján", importe: 7800 },
  { localidad: "Crucecita", zona: "Zona 2 - Avellaneda", importe: 4600 },
  { localidad: "Cuartel V", zona: "Zona 3 - Moreno", importe: 5500 },
  { localidad: "Del Viso (J.C. Paz)", zona: "Zona 3 - José C. Paz", importe: 5500 },
  { localidad: "Del Viso (Pilar)", zona: "Zona 4 - Pilar", importe: 7800 },
  { localidad: "Derqui", zona: "Zona 4 - Pilar", importe: 7800 },
  { localidad: "Dique Luján", zona: "Zona 4 - Tigre", importe: 7800 },
  { localidad: "Dock Sud", zona: "Zona 2 - Avellaneda", importe: 4600 },
  { localidad: "Domselaar", zona: "Zona 4 - San Vicente", importe: 7800 },
  { localidad: "Don Bosco", zona: "Zona 3 - Quilmes", importe: 5500 },
  { localidad: "Don Torcuato", zona: "Zona 3 - Tigre", importe: 5500 },
  { localidad: "El Jagüel", zona: "Zona 3 - Esteban Echeverría", importe: 5500 },
  { localidad: "El Palomar", zona: "Zona 2 - Morón", importe: 4600 },
  { localidad: "El Pato", zona: "Zona 3 - Berazategui", importe: 5500 },
  { localidad: "El Talar", zona: "Zona 3 - Tigre", importe: 5500 },
  { localidad: "Ensenada", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "Escalada (Zárate)", zona: "Zona 4 - Zárate", importe: 7800 },
  { localidad: "Escobar", zona: "Zona 4 - Escobar", importe: 7800 },
  { localidad: "Esteban Echeverría", zona: "Zona 3 - Esteban Echeverría", importe: 5500 },
  { localidad: "Ezeiza", zona: "Zona 3 - Ezeiza", importe: 5500 },
  { localidad: "Ezpeleta", zona: "Zona 3 - Quilmes", importe: 5500 },
  { localidad: "Florencio Varela", zona: "Zona 3 - Florencio Varela", importe: 5500 },
  { localidad: "Flores", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Floresta", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Florida", zona: "Zona 2 - Vicente López", importe: 4600 },
  { localidad: "Florida Oeste", zona: "Zona 2 - Vicente López", importe: 4600 },
  { localidad: "Francisco Álvarez", zona: "Zona 3 - Moreno", importe: 5500 },
  { localidad: "Fátima", zona: "Zona 4 - Pilar", importe: 7800 },
  { localidad: "Garín", zona: "Zona 4 - Escobar", importe: 7800 },
  { localidad: "General Pacheco", zona: "Zona 3 - Tigre", importe: 5500 },
  { localidad: "General Rodríguez", zona: "Zona 4 - General Rodríguez", importe: 7800 },
  { localidad: "General Rolón", zona: "Zona 4 - Zárate", importe: 7800 },
  { localidad: "Gerli (Avellaneda)", zona: "Zona 2 - Avellaneda", importe: 4600 },
  { localidad: "Gerli (Lanús)", zona: "Zona 2 - Lanús", importe: 4600 },
  { localidad: "Glew", zona: "Zona 3 - Almirante Brown", importe: 5500 },
  { localidad: "Gobernador Costa", zona: "Zona 3 - Florencio Varela", importe: 5500 },
  { localidad: "Gonnet", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "Gonzales Catán", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "González Catán", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "Gral. Rodríguez", zona: "Zona 4 - General Rodríguez", importe: 7800 },
  { localidad: "Grand Bourg", zona: "Zona 3 - Malvinas Argentinas", importe: 5500 },
  { localidad: "Gregorio de Laferrere", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "Guernica", zona: "Zona 4 - Presidente Perón", importe: 7800 },
  { localidad: "Haedo", zona: "Zona 2 - Morón", importe: 4600 },
  { localidad: "Hernández", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "Hudson", zona: "Zona 3 - Berazategui", importe: 5500 },
  { localidad: "Hurlingham", zona: "Zona 2 - Hurlingham", importe: 4600 },
  { localidad: "Ingeniero Adolfo Sourdeaux", zona: "Zona 3 - Malvinas Argentinas", importe: 5500 },
  { localidad: "Ingeniero Allan", zona: "Zona 3 - Florencio Varela", importe: 5500 },
  { localidad: "Ingeniero Budge", zona: "Zona 2 - Lomas de Zamora", importe: 4600 },
  { localidad: "Ingeniero Maschwitz", zona: "Zona 4 - Escobar", importe: 7800 },
  { localidad: "Ingeniero Pablo Nogués", zona: "Zona 3 - Malvinas Argentinas", importe: 5500 },
  { localidad: "Isidro Casanova", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "Ituzaingó", zona: "Zona 2 - Ituzaingó", importe: 4600 },
  { localidad: "Joaquín Gorina", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "José C. Paz", zona: "Zona 3 - José C. Paz", importe: 5500 },
  { localidad: "José Ingenieros", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "José León Suárez", zona: "Zona 2 - San Martín", importe: 4600 },
  { localidad: "José Mármol", zona: "Zona 3 - Almirante Brown", importe: 5500 },
  { localidad: "Juan María Gutiérrez", zona: "Zona 3 - Berazategui", importe: 5500 },
  { localidad: "Jáuregui", zona: "Zona 4 - Luján", importe: 7800 },
  { localidad: "Korn", zona: "Zona 4 - San Vicente", importe: 7800 },
  { localidad: "La Boca", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "La Lonja", zona: "Zona 4 - Pilar", importe: 7800 },
  { localidad: "La Lucila", zona: "Zona 2 - Vicente López", importe: 4600 },
  { localidad: "La Matanza Norte", zona: "Zona 2 - La Matanza Norte", importe: 4600 },
  { localidad: "La Matanza Sur", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "La Paternal", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "La Plata", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "La Plata Centro", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "La Reja", zona: "Zona 3 - Moreno", importe: 5500 },
  { localidad: "La Tablada", zona: "Zona 2 - La Matanza Norte", importe: 4600 },
  { localidad: "La Unión", zona: "Zona 3 - Ezeiza", importe: 5500 },
  { localidad: "Laferrere", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "Lanús", zona: "Zona 2 - Lanús", importe: 4600 },
  { localidad: "Lanús Este", zona: "Zona 2 - Lanús", importe: 4600 },
  { localidad: "Lanús Oeste", zona: "Zona 2 - Lanús", importe: 4600 },
  { localidad: "Libertad", zona: "Zona 3 - Merlo", importe: 5500 },
  { localidad: "Lima", zona: "Zona 4 - Zárate", importe: 7800 },
  { localidad: "Liniers", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Llavallol", zona: "Zona 2 - Lomas de Zamora", importe: 4600 },
  { localidad: "Loma Hermosa", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Loma Verde", zona: "Zona 4 - Escobar", importe: 7800 },
  { localidad: "Lomas de Zamora", zona: "Zona 2 - Lomas de Zamora", importe: 4600 },
  { localidad: "Lomas del Mirador", zona: "Zona 2 - La Matanza Norte", importe: 4600 },
  { localidad: "Longchamps", zona: "Zona 3 - Almirante Brown", importe: 5500 },
  { localidad: "Los Cardales", zona: "Zona 4 - Campana", importe: 7800 },
  { localidad: "Los Hornos", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "Los Polvorines", zona: "Zona 3 - Malvinas Argentinas", importe: 5500 },
  { localidad: "Luis Guillón", zona: "Zona 3 - Esteban Echeverría", importe: 5500 },
  { localidad: "Luján", zona: "Zona 4 - Luján", importe: 7800 },
  { localidad: "Luján Centro", zona: "Zona 4 - Luján", importe: 7800 },
  { localidad: "Malvinas Argentinas", zona: "Zona 3 - Malvinas Argentinas", importe: 5500 },
  { localidad: "Malvinas Argentinas (Alte. Brown)", zona: "Zona 3 - Almirante Brown", importe: 5500 },
  { localidad: "Manuel B. Gonnet", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "Manzanares", zona: "Zona 4 - Pilar", importe: 7800 },
  { localidad: "Maquinista Savio", zona: "Zona 4 - Escobar", importe: 7800 },
  { localidad: "Marcos Paz", zona: "Zona 4 - Marcos Paz", importe: 7800 },
  { localidad: "Mariano Acosta", zona: "Zona 3 - Merlo", importe: 5500 },
  { localidad: "Martín Coronado", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Martínez", zona: "Zona 2 - San Isidro", importe: 4600 },
  { localidad: "Mataderos", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Matheu", zona: "Zona 4 - Escobar", importe: 7800 },
  { localidad: "Merlo", zona: "Zona 3 - Merlo", importe: 5500 },
  { localidad: "Ministro Rivadavia", zona: "Zona 3 - Almirante Brown", importe: 5500 },
  { localidad: "Monserrat", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Monte Castro", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Monte Chingolo", zona: "Zona 2 - Lanús", importe: 4600 },
  { localidad: "Monte Grande", zona: "Zona 3 - Esteban Echeverría", importe: 5500 },
  { localidad: "Moreno", zona: "Zona 3 - Moreno", importe: 5500 },
  { localidad: "Morón", zona: "Zona 2 - Morón", importe: 4600 },
  { localidad: "Munro", zona: "Zona 2 - Vicente López", importe: 4600 },
  { localidad: "Muñiz", zona: "Zona 3 - San Miguel", importe: 5500 },
  { localidad: "Máximo Paz", zona: "Zona 4 - Cañuelas", importe: 7800 },
  { localidad: "Nordelta", zona: "Zona 3 - Tigre", importe: 5500 },
  { localidad: "Nueva Pompeya", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Núñez", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Olivera", zona: "Zona 4 - Luján", importe: 7800 },
  { localidad: "Olivos", zona: "Zona 2 - Vicente López", importe: 4600 },
  { localidad: "Once de Septiembre", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Open Door", zona: "Zona 4 - Luján", importe: 7800 },
  { localidad: "Pablo Nogués", zona: "Zona 3 - Malvinas Argentinas", importe: 5500 },
  { localidad: "Pablo Podestá", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Palermo", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Parque Avellaneda", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Parque Chacabuco", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Parque Chas", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Parque Leloir", zona: "Zona 2 - Ituzaingó", importe: 4600 },
  { localidad: "Parque Patricios", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Parque San Martín", zona: "Zona 3 - Merlo", importe: 5500 },
  { localidad: "Paso del Rey", zona: "Zona 3 - Moreno", importe: 5500 },
  { localidad: "Pilar", zona: "Zona 4 - Pilar", importe: 7800 },
  { localidad: "Pilar Centro", zona: "Zona 4 - Pilar", importe: 7800 },
  { localidad: "Piñeyro", zona: "Zona 2 - Avellaneda", importe: 4600 },
  { localidad: "Plátanos", zona: "Zona 3 - Berazategui", importe: 5500 },
  { localidad: "Pontevedra", zona: "Zona 3 - Merlo", importe: 5500 },
  { localidad: "Presidente Derqui", zona: "Zona 4 - Pilar", importe: 7800 },
  { localidad: "Presidente Perón", zona: "Zona 4 - Presidente Perón", importe: 7800 },
  { localidad: "Puerto Madero", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Quilmes", zona: "Zona 3 - Quilmes", importe: 5500 },
  { localidad: "Rafael Calzada", zona: "Zona 3 - Almirante Brown", importe: 5500 },
  { localidad: "Rafael Castillo", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "Rafael Castillos", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "Ramos Mejía", zona: "Zona 2 - La Matanza Norte", importe: 4600 },
  { localidad: "Ranelagh", zona: "Zona 3 - Berazategui", importe: 5500 },
  { localidad: "Recoleta", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Remedios de Escalada", zona: "Zona 2 - Lanús", importe: 4600 },
  { localidad: "Retiro", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Ricardo Rojas", zona: "Zona 3 - Tigre", importe: 5500 },
  { localidad: "Rincón de Milberg", zona: "Zona 3 - Tigre", importe: 5500 },
  { localidad: "Ringuelet", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "Saavedra", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "San Andrés", zona: "Zona 2 - San Martín", importe: 4600 },
  { localidad: "San Antonio de Padua", zona: "Zona 3 - Merlo", importe: 5500 },
  { localidad: "San Carlos", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "San Cristóbal", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "San Fernando", zona: "Zona 2 - San Fernando", importe: 4600 },
  { localidad: "San Francisco Solano (Alte. Brown)", zona: "Zona 3 - Almirante Brown", importe: 5500 },
  { localidad: "San Francisco Solano (Quilmes)", zona: "Zona 3 - Quilmes", importe: 5500 },
  { localidad: "San Isidro", zona: "Zona 2 - San Isidro", importe: 4600 },
  { localidad: "San Justo", zona: "Zona 2 - La Matanza Norte", importe: 4600 },
  { localidad: "San Martín", zona: "Zona 2 - San Martín", importe: 4600 },
  { localidad: "San Miguel", zona: "Zona 3 - San Miguel", importe: 5500 },
  { localidad: "San Nicolás", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "San Telmo", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "San Vicente", zona: "Zona 4 - San Vicente", importe: 7800 },
  { localidad: "San Vicente Centro", zona: "Zona 4 - San Vicente", importe: 7800 },
  { localidad: "Santa María", zona: "Zona 3 - San Miguel", importe: 5500 },
  { localidad: "Santos Lugares", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Sarandí", zona: "Zona 2 - Avellaneda", importe: 4600 },
  { localidad: "Savio", zona: "Zona 4 - Escobar", importe: 7800 },
  { localidad: "Sourigues", zona: "Zona 3 - Berazategui", importe: 5500 },
  { localidad: "Sáenz Peña", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Tapiales", zona: "Zona 2 - La Matanza Norte", importe: 4600 },
  { localidad: "Temperley", zona: "Zona 2 - Lomas de Zamora", importe: 4600 },
  { localidad: "Tierras Altas", zona: "Zona 3 - Malvinas Argentinas", importe: 5500 },
  { localidad: "Tigre", zona: "Zona 3 - Tigre", importe: 5500 },
  { localidad: "Tolosa", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "Torres", zona: "Zona 4 - Luján", importe: 7800 },
  { localidad: "Tortuguitas", zona: "Zona 3 - Malvinas Argentinas", importe: 5500 },
  { localidad: "Tres de Febrero", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Tristán Suárez", zona: "Zona 3 - Ezeiza", importe: 5500 },
  { localidad: "Troncos del Talar", zona: "Zona 3 - Tigre", importe: 5500 },
  { localidad: "Trujui", zona: "Zona 3 - Moreno", importe: 5500 },
  { localidad: "Turdera", zona: "Zona 2 - Lomas de Zamora", importe: 4600 },
  { localidad: "Uribelarrea", zona: "Zona 4 - Cañuelas", importe: 7800 },
  { localidad: "Valentín Alsina", zona: "Zona 2 - Lanús", importe: 4600 },
  { localidad: "Versalles", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Vicente Casares", zona: "Zona 4 - Cañuelas", importe: 7800 },
  { localidad: "Vicente López", zona: "Zona 2 - Vicente López", importe: 4600 },
  { localidad: "Victoria", zona: "Zona 2 - San Fernando", importe: 4600 },
  { localidad: "Villa Adelina (S. Isidro)", zona: "Zona 2 - San Isidro", importe: 4600 },
  { localidad: "Villa Adelina (V. López)", zona: "Zona 2 - Vicente López", importe: 4600 },
  { localidad: "Villa Astolfi", zona: "Zona 4 - Pilar", importe: 7800 },
  { localidad: "Villa Ballester", zona: "Zona 2 - San Martín", importe: 4600 },
  { localidad: "Villa Bosch", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Villa Brown", zona: "Zona 3 - Florencio Varela", importe: 5500 },
  { localidad: "Villa Celina", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "Villa Centenario", zona: "Zona 2 - Lomas de Zamora", importe: 4600 },
  { localidad: "Villa Crespo", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa de Mayo", zona: "Zona 3 - Malvinas Argentinas", importe: 5500 },
  { localidad: "Villa del Parque", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Devoto", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Domínico", zona: "Zona 2 - Avellaneda", importe: 4600 },
  { localidad: "Villa Elisa", zona: "Zona 4 - La Plata", importe: 7800 },
  { localidad: "Villa España", zona: "Zona 3 - Berazategui", importe: 5500 },
  { localidad: "Villa Fiorito", zona: "Zona 2 - Lomas de Zamora", importe: 4600 },
  { localidad: "Villa Fox", zona: "Zona 4 - Zárate", importe: 7800 },
  { localidad: "Villa General Mitre", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Insuperable", zona: "Zona 2 - La Matanza Norte", importe: 4600 },
  { localidad: "Villa la Ñata", zona: "Zona 4 - Tigre", importe: 7800 },
  { localidad: "Villa Lugano", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Luro", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Luzuriaga", zona: "Zona 2 - La Matanza Norte", importe: 4600 },
  { localidad: "Villa Lynch", zona: "Zona 2 - San Martín", importe: 4600 },
  { localidad: "Villa Madero", zona: "Zona 2 - La Matanza Norte", importe: 4600 },
  { localidad: "Villa Maipú", zona: "Zona 2 - San Martín", importe: 4600 },
  { localidad: "Villa Ortúzar", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Pueyrredón", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Raffo", zona: "Zona 2 - Tres de Febrero", importe: 4600 },
  { localidad: "Villa Real", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Riachuelo", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Rosa", zona: "Zona 4 - Pilar", importe: 7800 },
  { localidad: "Villa San Luis", zona: "Zona 3 - Florencio Varela", importe: 5500 },
  { localidad: "Villa Santa Rita", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Sarmiento", zona: "Zona 2 - Morón", importe: 4600 },
  { localidad: "Villa Soldati", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Tesei", zona: "Zona 2 - Hurlingham", importe: 4600 },
  { localidad: "Villa Udaondo", zona: "Zona 2 - Ituzaingó", importe: 4600 },
  { localidad: "Villa Urquiza", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Villa Vatteone", zona: "Zona 3 - Florencio Varela", importe: 5500 },
  { localidad: "Virrey del Pino", zona: "Zona 3 - La Matanza Sur", importe: 5500 },
  { localidad: "Virreyes", zona: "Zona 2 - San Fernando", importe: 4600 },
  { localidad: "Vélez Sársfield", zona: "Zona 1 - CABA", importe: 3500 },
  { localidad: "Wilde", zona: "Zona 2 - Avellaneda", importe: 4600 },
  { localidad: "William Morris", zona: "Zona 2 - Hurlingham", importe: 4600 },
  { localidad: "Zeballos", zona: "Zona 3 - Florencio Varela", importe: 5500 },
  { localidad: "Zárate", zona: "Zona 4 - Zárate", importe: 7800 },
  { localidad: "Zárate Centro", zona: "Zona 4 - Zárate", importe: 7800 },
];
